name: CI
on: [push, pull_request]

jobs:
  turbo:
    runs-on: ubuntu-latest
    strategy:
      matrix: { node: [20] }
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 8, run_install: false }
      - name: Restore cached .pnpm-store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm install --frozen-lockfile
      - run: pnpm turbo run lint typecheck test build --parallel
